package parser;

/* Generated By:JJTree: Do not edit this line. ASTConditionalAndExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditionalAndExp extends SimpleNode {
  public ASTConditionalAndExp(int id) {
    super(id);
  }

  public ASTConditionalAndExp(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5df69da622c69afd2a8a1b0712b4702e (do not edit this line) */
