package parser;

/* Generated By:JJTree: Do not edit this line. ASTConditionalOrExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditionalOrExp extends SimpleNode {
  public ASTConditionalOrExp(int id) {
    super(id);
  }

  public ASTConditionalOrExp(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=301daab165a5be4b261256b59c4c3e3f (do not edit this line) */
