package parser;

/* Generated By:JJTree: Do not edit this line. ASTConditionalEqExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditionalEqExp extends SimpleNode {
  public ASTConditionalEqExp(int id) {
    super(id);
  }

  public ASTConditionalEqExp(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2a4f4a99167c31be7682c05758ded65e (do not edit this line) */
