package parser;

/* Generated By:JJTree: Do not edit this line. ASTElseStmnt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseStmnt extends SimpleNode {
  public ASTElseStmnt(int id) {
    super(id);
  }

  public ASTElseStmnt(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6afee5e083cc38aafd7859c74b3f8425 (do not edit this line) */
