package parser;

/* Generated By:JJTree: Do not edit this line. ASTForStmnt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTForStmnt extends SimpleNode {
  public ASTForStmnt(int id) {
    super(id);
  }

  public ASTForStmnt(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c2be089f789a3c5d7fef8d8b680eb942 (do not edit this line) */
