package parser;

/* Generated By:JJTree: Do not edit this line. ASTFunctionOrId.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionOrId extends SimpleNode {
  public ASTFunctionOrId(int id) {
    super(id);
  }

  public ASTFunctionOrId(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9093c19ed7bff5a409490ac031a58b4f (do not edit this line) */
