package parser;

/* Generated By:JJTree: Do not edit this line. ASTFile.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFile extends SimpleNode {
  public ASTFile(int id) {
    super(id);
  }

  public ASTFile(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f7c3a1222d6a7c2a93d881d51d7d01e (do not edit this line) */
