package parser;

/* Generated By:JJTree: Do not edit this line. ASTMsgSuffix.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMsgSuffix extends SimpleNode {
  public ASTMsgSuffix(int id) {
    super(id);
  }

  public ASTMsgSuffix(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b2cad2dca05625fc66723c079d23cfdb (do not edit this line) */
