package parser;

/* Generated By:JJTree: Do not edit this line. ASTParams.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParams extends SimpleNode {
  public ASTParams(int id) {
    super(id);
  }

  public ASTParams(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ca7578c543aa62f408323891f77ae4c8 (do not edit this line) */
