package parser;

/* Generated By:JJTree: Do not edit this line. ASTSimExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSimExp extends SimpleNode {
  public ASTSimExp(int id) {
    super(id);
  }

  public ASTSimExp(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c95e855fa625d682f78ce4b9e0cb827b (do not edit this line) */
