package parser;

/* Generated By:JavaCC: Do not edit this line. Eg12TreeConstants.java Version 7.0.11 */
public interface Eg12TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFORSTMNT = 2;
  public int JJTIFSTMNT = 3;
  public int JJTELSESTMNT = 4;
  public int JJTASSERTSTMNT = 5;
  public int JJTDECLSTMNT = 6;
  public int JJTEXPRESSION = 7;
  public int JJTCONDITIONALOREXP = 8;
  public int JJTCONDITIONALANDEXP = 9;
  public int JJTCONDITIONALEQEXP = 10;
  public int JJTMSGSTMNT = 11;
  public int JJTMSGSUFFIX = 12;
  public int JJTFUNCTIONORID = 13;
  public int JJTFUNCTIONTAIL = 14;
  public int JJTSIMEXP = 15;
  public int JJTEXISTS = 16;
  public int JJTNOT = 17;
  public int JJTPARAMS = 18;
  public int JJTLITERAL = 19;
  public int JJTIDENTIFIER = 20;
  public int JJTTYPE = 21;
  public int JJTFILE = 22;
  public int JJTCLASS = 23;
  public int JJTMETHOD = 24;
  public int JJTFIELD = 25;
  public int JJTSTRING = 26;
  public int JJTBOOL = 27;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "ForStmnt",
    "IfStmnt",
    "ElseStmnt",
    "AssertStmnt",
    "DeclStmnt",
    "Expression",
    "ConditionalOrExp",
    "ConditionalAndExp",
    "ConditionalEqExp",
    "MsgStmnt",
    "MsgSuffix",
    "FunctionOrId",
    "FunctionTail",
    "SimExp",
    "Exists",
    "Not",
    "Params",
    "Literal",
    "Identifier",
    "Type",
    "File",
    "Class",
    "Method",
    "Field",
    "String",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=ef947b50188dba0a035bf76aad627ede (do not edit this line) */
