package parser;

/* Generated By:JavaCC: Do not edit this line. Eg12Visitor.java Version 7.0.11 */
public interface Eg12Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTForStmnt node, Object data);
  public Object visit(ASTIfStmnt node, Object data);
  public Object visit(ASTElseStmnt node, Object data);
  public Object visit(ASTAssertStmnt node, Object data);
  public Object visit(ASTDeclStmnt node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTConditionalOrExp node, Object data);
  public Object visit(ASTConditionalAndExp node, Object data);
  public Object visit(ASTConditionalEqExp node, Object data);
  public Object visit(ASTMsgStmnt node, Object data);
  public Object visit(ASTMsgSuffix node, Object data);
  public Object visit(ASTFunctionOrId node, Object data);
  public Object visit(ASTFunctionTail node, Object data);
  public Object visit(ASTSimExp node, Object data);
  public Object visit(ASTExists node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTParams node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTFile node, Object data);
  public Object visit(ASTClass node, Object data);
  public Object visit(ASTMethod node, Object data);
  public Object visit(ASTField node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTBool node, Object data);
}
/* JavaCC - OriginalChecksum=0f0bce86af519fe295dbdd796dea8884 (do not edit this line) */
